# Generated by Django 5.1 on 2024-08-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff_card',
            name='global_tag',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuff_card',
            name='local_tag',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stuff_card',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
